/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        navbarIconsNormal: "rgb(var(--navbar-icons-normal))",
        navbarIconsSelected: "rgb(var(--navbar-icons-selected))",
        navbarSearch: "rgb(var(--navbar-search))",
        navbarSearchBorder: "rgb(var(--navbar-search-border))",
        mainBackground: "rgb(var(--main-background))",
        cardBackground: "rgb(var(--card-background))",
        cardBackgroundHover: "rgb(var(--card-background-hover))",
        inputBackground: "rgb(var(--input-background))",
        inputBackgroundHover: "rgb(var(--input-background-hover))",
        cardBorder: "rgb(var(--card-border))",
        background: "rgb(var(--background))",
        boxbackground: "rgb(var(--boxbackground))",
        boxheading: "rgb(var(--boxheading))",
        postsbuttoncolor: "rgb(var(--postsbuttoncolor))",
        text: "rgb(var(--text))",
        companyheader: "rgb(var(--companyheader))",
        companyheader1: "rgb(var(--companyheader1))",
        companysubheader: "rgb(var(--companysubheader))",
        navbuttons: "rgb(var(--navbuttons))",
        overview: "rgb(var(--overview))",
        overviewcomponenttext: "rgb(var(--overviewcomponenttext))",
        postsslider: "rgb(var(--postsslider))",
        normaltext: "rgb(var(--normaltext))",
        modalbackground: "rgba(var(--modalbackground), 0.6)",
        sliderbutton: "rgb(var(--sliderbutton))",
        uploadimage: "rgb(var(--uploadimage))",
        mainBackground: "rgb(var(--main-background))",
        cardBackground: "rgb(var(--card-background))",
        cardBackgroundHover: "rgb(var(--card-background-hover))",
        card: "rgb(var(--card-border))",
        itemBorder: "rgb(var(--item-border))",
        itemBorderFocus: "rgb(var(--item-border-focus))",
        textTitle: "rgb(var(--text-title))",
        textHeavyTitle: "rgb(var(--text-heavy-title))",
        textHeavyTitleHover: "rgb(var(--text-heavy-title-hover))",
        textHomeTitle: "rgb(var(--text-home-title))",
        textDate: "rgb(var(--text-date))",
        textBreakpoint: "rgb(var(--text-breakpoint))",
        textContent: "rgb(var(--text-content))",
        textPlaceholder: "rgb(var(--text-placeholder))",
        textPlaceholderHover: "rgb(var(--text-placeholder-hover))",
        textActivity: "rgb(var(--text-activity))",
        textActivityHover: "rgb(var(--text-activity-hover))",
        textLightActivity: "rgb(var(--text-light-activity))",
        header: "rgb(var(--header))",
        authorName: "rgb(var(--author-name))",
        authorNameHover: "rgb(var(--author-name-hover))",
        authorBio: "rgb(var(--author-bio))",
        form: "rgb(var(--form))",
        icon: "rgb(var(--icon))",
        buttonIconHover: "rgb(var(--button-icon-hover))",
        buttonSubmitDisable: "rgb(var(--button-submit-disable))",
        buttonSubmitEnable: "rgb(var(--button-submit-enable))",
        buttonSubmitEnableHover: "rgb(var(--button-submit-enable-hover))",
        buttonSubmitText: "rgb(var(--button-submit-text))",
        listSelected: "rgb(var(--list-selected))",
        selectedjob: "rgb(var(--selectedjob))",
        itemBorderHover: "rgb(var(--item-border-hover))",
        buttonHover: "rgb(var(--button-hover))",
        error: "rgb(var(--error))",
        errorDark: "rgb(var(--error-dark))",
        amberLight: "rgb(var(--amber-light))",
        amberDark: "rgb(var(--amber-dark))",
        amberLightHover: "rgb(var(--amber-light-hover))",
        amberDarkHover: "rgb(var(--amber-dark-hover))",
        amberTextLight: "rgb(var(--amber-text-light))",
        amberTextDark: "rgb(var(--amber-text-dark))",
      },
    },
  },
  plugins: [],
};
