const posts = [
  {
    companyName: "ELSEWEDY ELECTRIC",
    logo: "src/assets/images/elsewedyicon.jpeg",
    timeAgo: "1w",
    text: "Elsewedy Cables, Safety That Lasts.",
    media: "src/assets/images/testpost.jpeg",
    mediaType: "image",
    likes: 687,
    comments: 11,
    shares: 132,
    edited: true,
  },
  {
    companyName: "Tech Innovators",
    logo: "src/assets/images/elsewedyicon.jpeg",
    timeAgo: "3d",
    text: "Our latest innovation is here! Stay tuned for the big reveal. 🚀",
    media: "src/assets/images/elsewedyicon.jpeg",
    mediaType: "image",
    likes: 450,
    comments: 20,
    shares: 75,
    edited: true,
  },
  {
    companyName: "AI Research Hub",
    logo: "src/assets/images/elsewedyicon.jpeg",
    timeAgo: "5d",
    text: "Read our latest article on the future of AI.",
    media: "src/assets/images/elsewedyicon.jpeg",
    mediaType: "image",
    likes: 310,
    comments: 15,
    shares: 80,
    edited: true,
  },
  {
    companyName: "Cloud Solutions",
    logo: "src/assets/images/elsewedyicon.jpeg",
    timeAgo: "2h",
    text: "Download our latest whitepaper on cloud security.",
    media: "src/assets/images/elsewedyicon.jpeg",
    mediaType: "image",
    likes: 220,
    comments: 8,
    shares: 50,
    edited: false,
  },
];

export default posts;
