const mockExperience = [
  {
    id: 1,
    title: "Software Engineer",
    company: "Google",
    location: "San Francisco, CA",
    startDate: "2020-06-01",
    endDate: "2023-08-31",
    description: "Worked on developing scalable web applications.",
    employmentType: "Full-time",
    locationType: "Onsite",
  },
  {
    id: 2,
    title: "Frontend Developer",
    company: "Microsoft",
    location: "Redmond, WA",
    startDate: "2018-07-01",
    endDate: "2020-05-31",
    description: "Built UI components for enterprise applications.",
    employmentType: "Full-time",
    locationType: "Hybrid",
  },
  {
    id: 3,
    title: "Software Engineer",
    company: "Google",
    location: "San Francisco, CA",
    startDate: "2020-06-01",
    endDate: "2023-08-31",
    description: "Worked on developing scalable web applications.",
    employmentType: "Full-time",
    locationType: "Onsite",
  },
  {
    id: 4,
    title: "Frontend Developer",
    company: "Microsoft",
    location: "Redmond, WA",
    startDate: "2018-07-01",
    endDate: "2020-05-31",
    description: "Built UI components for enterprise applications.",
    employmentType: "Full-time",
    locationType: "Hybrid",
  },
];

export default mockExperience;
