const mockEducation = [
  {
    id: 1,
    institution: "Harvard whatt",
    degree: "Bachelor's",
    field: "Computer Science",
    startDate: "2018-09-01",
    endDate: "2022-06-30",
    description: "Studied software engineering and AI.",
    grade: "3.9 GPA",
    activities: "tt",
  },
  {
    id: 2,
    institution: "Stanford University",
    degree: "Master's",
    field: "Artificial Intelligence",
    startDate: "2022-09-01",
    endDate: "2024-06-30",
    description: "Focused on deep learning and data science.",
    grade: "4.0 GPA",
    activities: "tt",
  },
  {
    id: 3,
    institution: "Harvard University",
    degree: "Bachelor's",
    field: "Computer Science",
    startDate: "2018-09-01",
    endDate: "2022-06-30",
    description: "Studied software engineering and AI.",
    grade: "3.9 GPA",
    activities: "tt",
  },
  {
    id: 4,
    institution: "Stanford University",
    degree: "Master's",
    field: "Artificial Intelligence",
    startDate: "2022-09-01",
    endDate: "2024-06-30",
    description: "Focused on deep learning and data science.",
    grade: "4.0 GPA",
    activities: "tt",
  },
];

export default mockEducation;
